---
# create subnets
- name: Create subnet
  ec2_vpc_subnet:
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    cidr:             "{{ item.aws_az_cidr }}"
    az:               "{{ item.aws_az }}"
    state:            "present"
  register: "pub_subnet_az"
  with_items: "{{ vpc_network_map_pub }}"

- debug:
    msg: "register id {{ item.subnet.id }} "
  with_items: "{{ pub_subnet_az }}"
