---
- name: Create and associate public network ACL with public subnets
  ec2_vpc_nacl:
    vpc_id: "{{ vpc_id }}"
    name:   "{{ vpc_name}}_public_networkacl"
    subnets: public_subnet_az_id_group
    ingress: [
        # rule no, protocol, allow/deny, cidr, icmp_code, icmp_type, port from, port to
        [100, 'tcp', 'allow', "{{ public_cidr }}", null, null, 80, 80],
        [110, 'tcp', 'allow', "{{ public_cidr }}", null, null, 443, 443],
        [120, 'tcp', 'allow', "{{ remote_cidr }}", null, null, 22, 22],
        [140, 'tcp', 'allow', "{{ public_cidr }}", null, null, 1024, 65535],
        [150, 'icmp', 'allow', "{{ vpc_cidr }}", -1, -1]
     ]
    egress: [
        [100, 'tcp', 'allow', "{{ public_cidr }}", null, null, 80, 80],
        [110, 'tcp', 'allow', "{{ public_cidr }}", null, null, 443, 443],
        [130, 'tcp', 'allow', "{{ private_subnet_az1_cidr }}", null, null, 3306, 3306],
        [131, 'tcp', 'allow', "{{ private_subnet_az2_cidr }}", null, null, 3306, 3306],
        [140, 'tcp', 'allow', "{{ public_cidr }}", null, null, 1024, 65535],
        [150, 'tcp', 'allow', "{{ private_subnet_az1_cidr }}", null, null, 22, 22],
        [151, 'tcp', 'allow', "{{ private_subnet_az2_cidr }}", null, null, 22, 22],
        [160, 'icmp', 'allow', "{{ public_cidr }}", -1, -1]
     ]
    state: "present"
