---
# create subnets
- name: Create subnet
  ec2_vpc_subnet:
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    cidr:             "{{ item.aws_az_cidr }}"
    az:               "{{ item.aws_az }}"
    state:            "present"
  register: "pub_subnet_az"
  with_items: "{{ vpc_network_map_pub }}"

- name: Create variable for AZ1 public subnet
  set_fact:
    public_subnet_az1_id: "{{ public_subnet_az1_id }} + ['{{ item.subnet.id }}']"
  with_items: "{{ pub_subnet_az.results }}"

- debug:
    msg: "{{ item }}"
  with_items: "{{ public_subnet_az1_id }}"
