---
# create private route table and connect to NAT

- name: Create AZ1 private route table
  ec2_vpc_route_table:
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    subnets: "{{ private_subnet_az_id_group }}"
#  with_items: "{{  }}"
