---
# create subnets
- name: Create subnet
  ec2_vpc_subnet:
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    cidr:             "{{ item.aws_az_cidr }}"
    az:               "{{ item.aws_az }}"
    state:            "present"
  register: "pvt_subnet_az"
  with_items: "{{ vpc_network_map_pvt }}"

- name: Create variable list for AZ public subnet
  set_fact:
    private_subnet_az_id_group: "{{ private_subnet_az_id_group }} + ['{{ item }}']"
  with_items: "{{ pvt_subnet_az.results.subnet }}"

# remove once the changes are tested
- debug:
    msg: "{{ item }}"
  with_items: "{{ private_subnet_az_id_group }}"
