---
# create private route table and connect to NAT

- name: Create AZ1 private route table
  ec2_vpc_route_table:
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    subnets:
      - "{{ item.private_subnet_az }}"
    routes:
      - dest: "{{ public_cidr }}"
        gateway_id: "{{ item.nat_gateway_id }}"
  with_items: "{{ pvt_az_nat_group }}"
