---
# tasks file for vpc-role

- name: Include YAML task to create VPC
  include_tasks: create_vpc.yml

- name: Include YAML task to create Internet gateway
  include_tasks: create_igw_vpc.yml

- name: Include YAML task to create public subnet
  include_tasks: create_pub_subnet.yml

- name: Include YAML task to create private subnet
  include_tasks: create_pvt_subnet.yml

- name: Include YAML task to create NAT gateway
  include_tasks: create_nat_gateway.yml

- name: Include YAML task to create public route table
  include_tasks: create_pub_route_tab.yml

- name: Include YAML task to create private route table
  include_tasks: create_pvt_route_tab.yml
