---
# "Removed ingress and egress rules - defaults to deny all"
- name: Create and associate public network ACL with public subnets
  ec2_vpc_nacl:
    region:           "{{ aws_region }}"
    vpc_id:           "{{ vpc_id }}"
    name:             "{{ vpc_name }}_public_networkacl"
    subnets:          "{{ item }}"
    ingress:          [
            # rule no, protocol, allow/deny, cidr, icmp_code, icmp_type, port from, port to
            [100, 'tcp', 'allow', '0.0.0.0/0', null, null, 80, 80],
            [110, 'tcp', 'allow', '0.0.0.0/0', null, null, 443, 443],
            [140, 'tcp', 'allow', '0.0.0.0/0', null, null, 1024, 65535]
    #        [150, 'icmp', 'allow', "{{ vpc_cidr }}", -1, -1]
         ]
    egress:           [
            [100, 'tcp', 'allow', '0.0.0.0/0', null, null, 80, 80],
            [110, 'tcp', 'allow', '0.0.0.0/0', null, null, 443, 443],
    #        [130, 'tcp', 'allow', "{{ private_subnet_az_cidr }}", null, null, 3306, 3306],
            [140, 'tcp', 'allow', '0.0.0.0/0', null, null, 1024, 65535]
    #        [150, 'tcp', 'allow', "{{ private_subnet_az1_cidr }}", null, null, 22, 22],
    #        [151, 'tcp', 'allow', "{{ private_subnet_az2_cidr }}", null, null, 22, 22],
    #        [160, 'icmp', 'allow', "{{ public_cidr }}", -1, -1]
         ]
    state: present
  register: "public_networkacl"
  with_items: "{{ public_subnet_az_id_group }}"

- name: Create variable for NACL id group
  set_fact:
    public_networkacl_id_group: "{{ public_networkacl_id_group }} + ['{{ item.nacl_id }}']"
  with_items: "{{ public_networkacl.results }}"

# remove once the changes are tested
- debug:
    msg: "{{ item }}"
  with_items: "{{ public_networkacl_id_group }}"
