---
# create security groups for instances in private subnet

- name: Create private instance security group
  ec2_group:
    name: "{{ private_sg_name }}"
    description: "Private instance security group"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto:      "tcp"
        from_port:  "80"
        to_port:    "80"
        group_name: "{{ private_sg_name }}"
      - proto:      "tcp"
        from_port:  "443"
        to_port:    "443"
        group_name: "{{ private_sg_name }}"
      - proto:      "tcp"
        from_port:  "22"
        to_port:    "22"
        cidr_ip:    "{{ vpc_cidr }}"
      - proto:      "tcp"
        from_port:  "3306"
        to_port:    "3306"
        cidr_ip:    "{{ vpc_cidr }}"
    rules_egress:
      - proto:      "tcp"
        from_port:  "80"
        to_port:    "80"
        cidr_ip:    "{{ public_cidr }}"
      - proto:      "tcp"
        from_port:  "443"
        to_port:    "443"
        cidr_ip:    "{{ public_cidr }}"
      - proto:      "tcp"
        from_port:  "22"
        to_port:    "22"
        group_name: "{{ private_sg_name }}"
  register: private_instance_sg

- name: Create variable for private instance security group id
  set_fact:
    private_instance_sg_id: "{{ private_instance_sg.group_id }}"
